algo = input('Digite algo: ')
print('É Alfanumérico?', algo.isalnum())
print('É Alfa?', algo.isalpha())
print('É Decimal?', algo.isdecimal())
print('É Dígito?', algo.isdigit())
print('É Identificador?', algo.isidentifier())
print('É Caixa baixa?', algo.islower())
print('É numérico?', algo.isnumeric())
print('É printável?', algo.isprintable())
print('É espaço?', algo.isspace())
print('É título?', algo.istitle())
print('É caixa alta?', algo.isupper())